services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

  backend:
    build: ./backend
    container_name: ecommerce-backend-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - ecommerce-net

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend-container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  postgres_data:

networks:
  ecommerce-net: